-- users 表字段注释
ALTER TABLE users MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID';
ALTER TABLE users MODIFY COLUMN username VARCHAR(50) NOT NULL COMMENT '用户名';
ALTER TABLE users MODIFY COLUMN email VARCHAR(100) NOT NULL COMMENT '邮箱';
ALTER TABLE users MODIFY COLUMN password VARCHAR(255) NOT NULL COMMENT '密码';
ALTER TABLE users MODIFY COLUMN avatar VARCHAR(500) DEFAULT '' COMMENT '头像';
ALTER TABLE users MODIFY COLUMN bio VARCHAR(500) DEFAULT '' COMMENT '简介';
ALTER TABLE users MODIFY COLUMN role VARCHAR(20) DEFAULT 'user' COMMENT '角色';
ALTER TABLE users MODIFY COLUMN level INT DEFAULT 1 COMMENT '等级';
ALTER TABLE users MODIFY COLUMN status INT DEFAULT 1 COMMENT '状态: 1=正常 0=封禁';
ALTER TABLE users MODIFY COLUMN article_count INT DEFAULT 0 COMMENT '文章数';
ALTER TABLE users MODIFY COLUMN follow_count INT DEFAULT 0 COMMENT '关注数';
ALTER TABLE users MODIFY COLUMN fans_count INT DEFAULT 0 COMMENT '粉丝数';

-- articles 表字段注释
ALTER TABLE articles MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '文章ID';
ALTER TABLE articles MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '作者ID';
ALTER TABLE articles MODIFY COLUMN title VARCHAR(200) NOT NULL COMMENT '标题';
ALTER TABLE articles MODIFY COLUMN content LONGTEXT COMMENT '内容';
ALTER TABLE articles MODIFY COLUMN summary VARCHAR(500) DEFAULT '' COMMENT '摘要';
ALTER TABLE articles MODIFY COLUMN cover VARCHAR(500) DEFAULT '' COMMENT '封面';
ALTER TABLE articles MODIFY COLUMN status VARCHAR(20) DEFAULT 'published' COMMENT '状态';
ALTER TABLE articles MODIFY COLUMN category_id BIGINT UNSIGNED COMMENT '分类ID';
ALTER TABLE articles MODIFY COLUMN tags VARCHAR(500) DEFAULT '[]' COMMENT '标签JSON';
ALTER TABLE articles MODIFY COLUMN view_count INT DEFAULT 0 COMMENT '浏览数';
ALTER TABLE articles MODIFY COLUMN like_count INT DEFAULT 0 COMMENT '点赞数';
ALTER TABLE articles MODIFY COLUMN comment_count INT DEFAULT 0 COMMENT '评论数';
ALTER TABLE articles MODIFY COLUMN favorite_count INT DEFAULT 0 COMMENT '收藏数';
ALTER TABLE articles MODIFY COLUMN is_ai TINYINT(1) DEFAULT 0 COMMENT '是否AI生成';

-- categories 表字段注释
ALTER TABLE categories MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '分类ID';
ALTER TABLE categories MODIFY COLUMN name VARCHAR(50) NOT NULL COMMENT '分类名';
ALTER TABLE categories MODIFY COLUMN sort INT DEFAULT 0 COMMENT '排序';

-- tags 表字段注释
ALTER TABLE tags MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '标签ID';
ALTER TABLE tags MODIFY COLUMN name VARCHAR(50) NOT NULL COMMENT '标签名';
ALTER TABLE tags MODIFY COLUMN color VARCHAR(7) DEFAULT '' COMMENT '颜色';
ALTER TABLE tags MODIFY COLUMN count BIGINT DEFAULT 0 COMMENT '使用次数';

-- comments 表字段注释
ALTER TABLE comments MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '评论ID';
ALTER TABLE comments MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID';
ALTER TABLE comments MODIFY COLUMN article_id BIGINT UNSIGNED NOT NULL COMMENT '文章ID';
ALTER TABLE comments MODIFY COLUMN parent_id BIGINT UNSIGNED DEFAULT 0 COMMENT '父评论ID';
ALTER TABLE comments MODIFY COLUMN content TEXT NOT NULL COMMENT '内容';

-- prompts 表字段注释
ALTER TABLE prompts MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Prompt ID';
ALTER TABLE prompts MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '作者ID';
ALTER TABLE prompts MODIFY COLUMN title VARCHAR(200) NOT NULL COMMENT '标题';
ALTER TABLE prompts MODIFY COLUMN content TEXT NOT NULL COMMENT '内容';
ALTER TABLE prompts MODIFY COLUMN description VARCHAR(500) DEFAULT '' COMMENT '描述';
ALTER TABLE prompts MODIFY COLUMN category VARCHAR(50) DEFAULT '' COMMENT '分类';
ALTER TABLE prompts MODIFY COLUMN model VARCHAR(50) DEFAULT '' COMMENT '适用模型';
ALTER TABLE prompts MODIFY COLUMN tags VARCHAR(500) DEFAULT '[]' COMMENT '标签JSON';
ALTER TABLE prompts MODIFY COLUMN usage_count BIGINT DEFAULT 0 COMMENT '使用次数';
ALTER TABLE prompts MODIFY COLUMN like_count BIGINT DEFAULT 0 COMMENT '点赞数';
ALTER TABLE prompts MODIFY COLUMN rating DOUBLE DEFAULT 0 COMMENT '评分';
ALTER TABLE prompts MODIFY COLUMN status INT DEFAULT 1 COMMENT '状态';

-- notifications 表字段注释
ALTER TABLE notifications MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '通知ID';
ALTER TABLE notifications MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '接收者ID';
ALTER TABLE notifications MODIFY COLUMN actor_id BIGINT UNSIGNED NOT NULL COMMENT '触发者ID';
ALTER TABLE notifications MODIFY COLUMN type VARCHAR(50) NOT NULL COMMENT '类型';
ALTER TABLE notifications MODIFY COLUMN content VARCHAR(500) DEFAULT '' COMMENT '内容';
ALTER TABLE notifications MODIFY COLUMN target_id BIGINT UNSIGNED COMMENT '目标ID';
ALTER TABLE notifications MODIFY COLUMN target_url VARCHAR(255) DEFAULT '' COMMENT '目标链接';
ALTER TABLE notifications MODIFY COLUMN is_read TINYINT(1) DEFAULT 0 COMMENT '是否已读';

-- likes 表字段注释
ALTER TABLE likes MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '点赞ID';
ALTER TABLE likes MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID';
ALTER TABLE likes MODIFY COLUMN target_type VARCHAR(20) NOT NULL COMMENT '目标类型';
ALTER TABLE likes MODIFY COLUMN target_id BIGINT UNSIGNED NOT NULL COMMENT '目标ID';

-- favorites 表字段注释
ALTER TABLE favorites MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '收藏ID';
ALTER TABLE favorites MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID';
ALTER TABLE favorites MODIFY COLUMN article_id BIGINT UNSIGNED NOT NULL COMMENT '文章ID';

-- follows 表字段注释
ALTER TABLE follows MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关注ID';
ALTER TABLE follows MODIFY COLUMN follower_id BIGINT UNSIGNED NOT NULL COMMENT '关注者ID';
ALTER TABLE follows MODIFY COLUMN followed_id BIGINT UNSIGNED NOT NULL COMMENT '被关注者ID';

-- announcements 表字段注释
ALTER TABLE announcements MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '公告ID';
ALTER TABLE announcements MODIFY COLUMN title VARCHAR(200) NOT NULL COMMENT '标题';
ALTER TABLE announcements MODIFY COLUMN content TEXT NOT NULL COMMENT '内容';
ALTER TABLE announcements MODIFY COLUMN status INT DEFAULT 1 COMMENT '状态';
ALTER TABLE announcements MODIFY COLUMN priority INT DEFAULT 0 COMMENT '优先级';
ALTER TABLE announcements MODIFY COLUMN author VARCHAR(50) DEFAULT '' COMMENT '作者';

-- reports 表字段注释
ALTER TABLE reports MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '举报ID';
ALTER TABLE reports MODIFY COLUMN reporter_id BIGINT UNSIGNED NOT NULL COMMENT '举报人ID';
ALTER TABLE reports MODIFY COLUMN target_type VARCHAR(20) NOT NULL COMMENT '目标类型';
ALTER TABLE reports MODIFY COLUMN target_id BIGINT UNSIGNED NOT NULL COMMENT '目标ID';
ALTER TABLE reports MODIFY COLUMN reason VARCHAR(500) NOT NULL COMMENT '举报原因';
ALTER TABLE reports MODIFY COLUMN status INT DEFAULT 0 COMMENT '状态';
ALTER TABLE reports MODIFY COLUMN result VARCHAR(200) DEFAULT '' COMMENT '处理结果';

-- audit_logs 表字段注释
ALTER TABLE audit_logs MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '日志ID';
ALTER TABLE audit_logs MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID';
ALTER TABLE audit_logs MODIFY COLUMN username VARCHAR(50) DEFAULT '' COMMENT '用户名';
ALTER TABLE audit_logs MODIFY COLUMN action VARCHAR(100) NOT NULL COMMENT '操作类型';
ALTER TABLE audit_logs MODIFY COLUMN target VARCHAR(200) DEFAULT '' COMMENT '操作对象';
ALTER TABLE audit_logs MODIFY COLUMN detail TEXT COMMENT '操作详情';
ALTER TABLE audit_logs MODIFY COLUMN ip VARCHAR(50) DEFAULT '' COMMENT 'IP地址';

-- system_configs 表字段注释
ALTER TABLE system_configs MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '配置ID';
ALTER TABLE system_configs MODIFY COLUMN key VARCHAR(100) NOT NULL COMMENT '配置键名';
ALTER TABLE system_configs MODIFY COLUMN value TEXT COMMENT '配置值';
ALTER TABLE system_configs MODIFY COLUMN desc VARCHAR(200) DEFAULT '' COMMENT '说明';

-- ai_usage_stats 表字段注释
ALTER TABLE ai_usage_stats MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '统计ID';
ALTER TABLE ai_usage_stats MODIFY COLUMN date VARCHAR(10) NOT NULL COMMENT '日期';
ALTER TABLE ai_usage_stats MODIFY COLUMN total_requests INT DEFAULT 0 COMMENT '总请求数';
ALTER TABLE ai_usage_stats MODIFY COLUMN total_tokens INT DEFAULT 0 COMMENT '总Token数';
ALTER TABLE ai_usage_stats MODIFY COLUMN prompt_tokens INT DEFAULT 0 COMMENT '提示Token数';
ALTER TABLE ai_usage_stats MODIFY COLUMN completion_tokens INT DEFAULT 0 COMMENT '生成Token数';
ALTER TABLE ai_usage_stats MODIFY COLUMN error_count INT DEFAULT 0 COMMENT '错误数';

-- user_bans 表字段注释
ALTER TABLE user_bans MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '封禁ID';
ALTER TABLE user_bans MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID';
ALTER TABLE user_bans MODIFY COLUMN reason VARCHAR(500) NOT NULL COMMENT '封禁原因';
ALTER TABLE user_bans MODIFY COLUMN ban_type VARCHAR(20) NOT NULL COMMENT '封禁类型';
ALTER TABLE user_bans MODIFY COLUMN expires_at DATETIME COMMENT '过期时间';
ALTER TABLE user_bans MODIFY COLUMN operator VARCHAR(50) DEFAULT '' COMMENT '操作人';

-- user_tags 表字段注释
ALTER TABLE user_tags MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '标签ID';
ALTER TABLE user_tags MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID';
ALTER TABLE user_tags MODIFY COLUMN tag VARCHAR(50) NOT NULL COMMENT '标签名';

-- sensitive_words 表字段注释
ALTER TABLE sensitive_words MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '词ID';
ALTER TABLE sensitive_words MODIFY COLUMN word VARCHAR(100) NOT NULL COMMENT '敏感词';
ALTER TABLE sensitive_words MODIFY COLUMN level INT DEFAULT 1 COMMENT '级别';
ALTER TABLE sensitive_words MODIFY COLUMN replace_to VARCHAR(100) DEFAULT '' COMMENT '替换内容';

-- content_reviews 表字段注释
ALTER TABLE content_reviews MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '审核ID';
ALTER TABLE content_reviews MODIFY COLUMN target_type VARCHAR(20) NOT NULL COMMENT '目标类型';
ALTER TABLE content_reviews MODIFY COLUMN target_id BIGINT UNSIGNED NOT NULL COMMENT '目标ID';
ALTER TABLE content_reviews MODIFY COLUMN status INT DEFAULT 0 COMMENT '状态';
ALTER TABLE content_reviews MODIFY COLUMN reviewer_id BIGINT UNSIGNED COMMENT '审核人ID';
ALTER TABLE content_reviews MODIFY COLUMN reason VARCHAR(500) DEFAULT '' COMMENT '审核原因';

-- recommend_items 表字段注释
ALTER TABLE recommend_items MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '推荐ID';
ALTER TABLE recommend_items MODIFY COLUMN target_type VARCHAR(20) NOT NULL COMMENT '目标类型';
ALTER TABLE recommend_items MODIFY COLUMN target_id BIGINT UNSIGNED NOT NULL COMMENT '目标ID';
ALTER TABLE recommend_items MODIFY COLUMN position VARCHAR(50) NOT NULL COMMENT '推荐位置';
ALTER TABLE recommend_items MODIFY COLUMN sort_order INT DEFAULT 0 COMMENT '排序';
ALTER TABLE recommend_items MODIFY COLUMN status INT DEFAULT 1 COMMENT '状态';

-- points_rules 表字段注释
ALTER TABLE points_rules MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '规则ID';
ALTER TABLE points_rules MODIFY COLUMN action VARCHAR(50) NOT NULL COMMENT '操作类型';
ALTER TABLE points_rules MODIFY COLUMN points INT NOT NULL COMMENT '积分值';
ALTER TABLE points_rules MODIFY COLUMN desc VARCHAR(200) DEFAULT '' COMMENT '说明';

-- invite_codes 表字段注释
ALTER TABLE invite_codes MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '邀请码ID';
ALTER TABLE invite_codes MODIFY COLUMN code VARCHAR(20) NOT NULL COMMENT '邀请码';
ALTER TABLE invite_codes MODIFY COLUMN creator_id BIGINT UNSIGNED COMMENT '创建者ID';
ALTER TABLE invite_codes MODIFY COLUMN used_by BIGINT UNSIGNED COMMENT '使用者ID';
ALTER TABLE invite_codes MODIFY COLUMN max_uses INT DEFAULT 1 COMMENT '最大使用次数';
ALTER TABLE invite_codes MODIFY COLUMN used_count INT DEFAULT 0 COMMENT '已使用次数';
ALTER TABLE invite_codes MODIFY COLUMN expires_at DATETIME COMMENT '过期时间';

-- login_logs 表字段注释
ALTER TABLE login_logs MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '日志ID';
ALTER TABLE login_logs MODIFY COLUMN user_id BIGINT UNSIGNED NOT NULL COMMENT '用户ID';
ALTER TABLE login_logs MODIFY COLUMN ip VARCHAR(50) DEFAULT '' COMMENT 'IP地址';
ALTER TABLE login_logs MODIFY COLUMN user_agent VARCHAR(500) DEFAULT '' COMMENT 'User Agent';
ALTER TABLE login_logs MODIFY COLUMN status INT DEFAULT 1 COMMENT '状态';

-- ip_blacklists 表字段注释
ALTER TABLE ip_blacklists MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录ID';
ALTER TABLE ip_blacklists MODIFY COLUMN ip VARCHAR(50) NOT NULL COMMENT 'IP地址';
ALTER TABLE ip_blacklists MODIFY COLUMN reason VARCHAR(200) DEFAULT '' COMMENT '封禁原因';
ALTER TABLE ip_blacklists MODIFY COLUMN expires_at DATETIME COMMENT '过期时间';

-- system_logs 表字段注释
ALTER TABLE system_logs MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '日志ID';
ALTER TABLE system_logs MODIFY COLUMN level VARCHAR(20) NOT NULL COMMENT '级别';
ALTER TABLE system_logs MODIFY COLUMN message TEXT NOT NULL COMMENT '消息';
ALTER TABLE system_logs MODIFY COLUMN source VARCHAR(100) DEFAULT '' COMMENT '来源';
ALTER TABLE system_logs MODIFY COLUMN stack TEXT COMMENT '堆栈';

-- page_views 表字段注释
ALTER TABLE page_views MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '记录ID';
ALTER TABLE page_views MODIFY COLUMN path VARCHAR(200) NOT NULL COMMENT '页面路径';
ALTER TABLE page_views MODIFY COLUMN user_id BIGINT UNSIGNED COMMENT '用户ID';
ALTER TABLE page_views MODIFY COLUMN ip VARCHAR(50) DEFAULT '' COMMENT 'IP地址';
ALTER TABLE page_views MODIFY COLUMN user_agent VARCHAR(500) DEFAULT '' COMMENT 'User Agent';