ALTER TABLE system_configs MODIFY COLUMN id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '配置ID';
ALTER TABLE system_configs MODIFY COLUMN key VARCHAR(100) NOT NULL COMMENT '配置键名';
ALTER TABLE system_configs MODIFY COLUMN value TEXT COMMENT '配置值';
ALTER TABLE system_configs MODIFY COLUMN desc VARCHAR(200) DEFAULT '' COMMENT '说明';