apiVersion: v1
kind: Secret
metadata:
  name: seckill-db-secret
  namespace: seckill
type: Opaque
stringData:
  mysql-root-password: "RootPass2024!Secure"
  mysql-user: "seckill"
  mysql-password: "SeckillDB2024!"
  mysql-url: "jdbc:mysql://mysql-service.seckill.svc.cluster.local:3306/user_system?useUnicode=true&characterEncoding=utf8mb4&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"

---

apiVersion: v1
kind: Secret
metadata:
  name: seckill-jwt-secret
  namespace: seckill
type: Opaque
stringData:
  jwt-secret: "prod-jwt-secret-key-change-this-in-production-environment-min-256-bits"

---

apiVersion: v1
kind: Secret
metadata:
  name: seckill-redis-secret
  namespace: seckill
type: Opaque
stringData:
  redis-password: "RedisSecure2024!"

---

apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: seckill
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJoYXJib3Iuc2Vja2lsbC5jb20iOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiSGFyYm9yMTIzNDUiLCJhdXRoIjoiWVdSdGFXNDZTR0Z5WW05eU1USXpORFU9In19fQ==