apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-service.monitoring.svc.cluster.local:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  - name: Loki
    type: loki
    access: proxy
    url: http://loki-service.logging.svc.cluster.local:3100
    editable: false
    jsonData:
      maxLines: 5000

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch-service.logging.svc.cluster.local:9200
    editable: false
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.0.0"
      interval: Daily
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level